MVC/DiaryApp/Models/DiaryEntry.cs
using System.ComponentModel.DataAnnotations;

namespace DiaryApp.Models;

public class DiaryEntry
{
    // [Key] -> EF Core knows by default that if you have a prop named Id that it is the Key  (PK). You use the Key data annotation if the name of the Id would be different, ex: DiaryEntryId
    public int Id { get; set; }

    [StringLength(100, MinimumLength = 3, ErrorMessage = "Title must be between 3 and 100 characters!")]
    [Required(ErrorMessage = "Please enter a Title!")]
    public string Title { get; set; } = string.Empty;

    [Required]
    public string Content { get; set; } = string.Empty;

    [Required]
    public DateTime Created { get; set; } = DateTime.Now;
}

MVC/DiaryApp/Models/ErrorViewModel.cs
namespace DiaryApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/DiaryApp/Controllers/DiaryEntriesController.cs
using DiaryApp.Data;
using DiaryApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DiaryApp.Controllers;

public class DiaryEntriesController : Controller
{
    #region Constructor and interfaces

    private readonly ApplicationDbContext _db;

    public DiaryEntriesController(ApplicationDbContext db)
    {
        _db = db;
    }

    #endregion Constructor and interfaces

    #region Public methods

    public IActionResult Index()
    {
        List<DiaryEntry> objDiaryEntryList = _db.DiaryEntries.ToList();

        return View(objDiaryEntryList);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public IActionResult Create(DiaryEntry diaryEntry)
    {
        if (diaryEntry != null && diaryEntry.Title.Length < 3)
        {
            //here we add an error to the Title property
            ModelState.AddModelError("Title", "The title must be at least 3 characters long!");
        }

        if (ModelState.IsValid)
        {
            _db.DiaryEntries.Add(diaryEntry);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        return View(diaryEntry);
    }

    public IActionResult Edit(int? id)
    {
        if (id is null || id == 0)
        {
            return NotFound();
        }

        DiaryEntry? diaryEntry = _db.DiaryEntries.Find(id);

        if (diaryEntry is null)
        {
            return NotFound();
        }

        return View(diaryEntry);
    }

    [HttpPost]
    public IActionResult Edit(DiaryEntry diaryEntry)
    {
        if (diaryEntry != null && diaryEntry.Title.Length < 3)
        {
            ModelState.AddModelError("Title", "The title must be at least 3 characters long!");
        }

        if (ModelState.IsValid)
        {
            _db.DiaryEntries.Update(diaryEntry);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        return View(diaryEntry);
    }

    public IActionResult Delete(int? id)
    {
        if (id is null || id == 0)
        {
            return NotFound();
        }

        DiaryEntry? diaryEntry = _db.DiaryEntries.Find(id);

        if (diaryEntry is null)
        {
            return NotFound();
        }

        return View(diaryEntry);
    }

    [HttpPost]
    public IActionResult Delete(DiaryEntry diaryEntry)
    {
        _db.DiaryEntries.Remove(diaryEntry);
        _db.SaveChanges();

        return RedirectToAction("Index");
    }

    #endregion Public methods
}

MVC/DiaryApp/Controllers/HomeController.cs
using System.Diagnostics;
using DiaryApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DiaryApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/DiaryApp/Views/DiaryEntries/Create.cshtml
@model DiaryEntry

@{
    ViewData["Title"] = "Create entry";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2>Create Diary Entry</h2>
                </div>
                <div class="card-body">
                    <form asp-action="Create" method="post">
                        <!--The asp-validation-summary="All" will show all of the validations for your model, these are based on what we have in our class :)-->
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group mb-3">
                            <label asp-for="Title" class="form-label">Title</label>
                            <input asp-for="Title" class="form-control" placeholder="Enter a title" type="text"  />
                            <!--we can also do something like this, it's a simpler way to add validation and this only focus for a given property of the model-->
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Content" class="form-label">Content</label>
                            <input asp-for="Content" row="5" class="form-control" placeholder="Enter what you did that day" type="text" />
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Created" class="form-label">Date</label>
                            <input asp-for="Created" class="form-control" type="date" />
                            <span asp-validation-for="Created" class="text-danger"></span>
                        </div>

                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Create</button>
                            <a asp-controller="DiaryEntries" asp-action="Index" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Here we are using the partial "_ValidationScriptsPartial" to use the jquery validate-->
<!--we can use the section Scripts to use the scripts that are inside the given view-->
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MVC/DiaryApp/Views/DiaryEntries/Delete.cshtml
@model DiaryEntry

@{
    ViewData["Title"] = "Delete entry";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2>Delete Diary Entry</h2>
                </div>
                <div class="card-body">
                    <form asp-action="Delete" method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group mb-3">
                            <label asp-for="Title" class="form-label">Title</label>
                            <input asp-for="Title" class="form-control" placeholder="Enter a title" type="text" disabled />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Content" class="form-label">Content</label>
                            <input asp-for="Content" row="5" class="form-control" placeholder="Enter what you did that day" type="text" disabled />
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Created" class="form-label">Date</label>
                            <input asp-for="Created" class="form-control" type="date" disabled />
                            <span asp-validation-for="Created" class="text-danger"></span>
                        </div>

                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <a asp-controller="DiaryEntries" asp-action="Index" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

MVC/DiaryApp/Views/DiaryEntries/Edit.cshtml
@model DiaryEntry

@{
    ViewData["Title"] = "Edit entry";
}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h2>Edit Diary Entry</h2>
                </div>
                <div class="card-body">
                    <form asp-action="Edit" method="post">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group mb-3">
                            <label asp-for="Title" class="form-label">Title</label>
                            <input asp-for="Title" class="form-control" placeholder="Enter a title" type="text" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Content" class="form-label">Content</label>
                            <input asp-for="Content" row="5" class="form-control" placeholder="Enter what you did that day" type="text" />
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>

                        <div class="form-group mb-3">
                            <label asp-for="Created" class="form-label">Date</label>
                            <input asp-for="Created" class="form-control" type="date" />
                            <span asp-validation-for="Created" class="text-danger"></span>
                        </div>

                        <div class="d-flex justify-content-between">
                            <button type="submit" class="btn btn-primary">Edit</button>
                            <a asp-controller="DiaryEntries" asp-action="Index" class="btn btn-secondary">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MVC/DiaryApp/Views/DiaryEntries/Index.cshtml
@model List<DiaryEntry>

@{
    ViewData["Title"] = "Entries";
}

<div class="container">
    <div class="row pt-4">
        <div class="col-6">
            <!-- asp-controller is que controller we want to make the call | asp-action is the action inside the controller | the asp-area is the folder where the controller is. These helper tags are inside the DLLs of the MVC.TagHelpers (it's being imported in the _ViewImports.cshtml) -->
            <a class="btn btn-primary" asp-controller="DiaryEntries" asp-action="Create">
                <i class="bi bi-journal-plus"></i> Create new diary entry
            </a>
        </div>
        <div class="col-6 text-end">
            <h2>Diary Entries</h2>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Content</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var entry in Model)
            {
                <tr>
                    <td>@entry.Title</td>
                    <td>@entry.Content</td>
                    <td>@entry.Created</td>
                    <td>
                        <!--we use asp-route-id="entry.Id" to pass the id of the diary entry to the route of the url, with this the id will be passed to our Edit endpoint in the controller-->
                        <a asp-controller="DiaryEntries" asp-action="Edit" asp-route-id="@entry.Id" class="btn btn-primary btn-sm">
                            <i class="bi bi-pencil"></i> Edit
                        </a>
                        <a asp-controller="DiaryEntries" asp-action="Delete" asp-route-id="@entry.Id" class="btn btn-danger btn-sm">
                            <i class="bi bi-trash"></i> Delete
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

MVC/DiaryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DiaryApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DiaryApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    My Diary
                    <i class="bi bi-journal-text"></i>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="DiaryEntries" asp-action="Index">My Entries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DiaryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--this part below (RenderSectionAsync) is used to render the section "Scripts inside each view-->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>